[general]
import = ["./thyrfing.toml"]

[window]
padding = { x = 8, y = 8 }
opacity = 0.9

[font]
normal = { family = "HackNerdFont" }
bold = { family = "HackNerdFont" }
italic = { family = "HackNerdFont" }

size = 10

[selection]
save_to_clipboard = true

